language: android
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
android:
  components:
  - build-tools-28.0.3
  - android-28
  - extra-android-m2repository
  - extra-android-support
before_install:
- chmod 755 gradlew
script:
- "./gradlew assembleDebug testRelease assembleRelease"
before_deploy: 
deploy:
  provider: releases
  api_key: "$GIT_TOKEN"
  file:
  - app/build/outputs/apk/release/app-release.apk
  - app/build/outputs/apk/debug/app-debug.apk
  file_glob: true
  skip_cleanup: true
  prerelease: true
  on:
    tags: true
    all_branches: true
env:
  global:
    secure: UyjHANahYryB7ckNLQzotaeKeoR9K7kbaji0W/CZVEJQFXLiW47tQG8Kwk+a2ub3/xVVh4X8oDIz6OxOMjWQs/u+rqRtamaaPpxof5KTz2gf8uk5dofSHm4n44AlcMV7W/uDYqJBqDbx37sGNsA0Vi3bNMkrCjXbs7JhdMSmNMJUD/nwvCISSVviTJXgwXWFyDp+8RymwL2PdhRxJYyeeC7bxA5A8cRGW+3C2RvbKQ5UM4ECuZMMXDyrpjK7Srt9HqFerAHPJpTYLFbOabJT9nSpOctCmEbHpI5DkeTzraOPRIqaXiFRJ28+OL6h/VDQ6tXm6Gzeqx6BijYWgL5NIxQvHL/3XfO98gGvUwuZuvBVEq3ksTmda26NpYlVpnwMIEn0uIQJeA5vp1y6xY9bExi0XItMbSZ0UaEGwWa8u4gEBx5xDtmeH8iN3M3MBcii/iYOyjBzLE3OrpeRULHgsyeEdwYxxF90Onl4gxLiJ8lVbWdEZ28NJqqTSu7elerjLW5ohnZxz6xTowiE41rO4CMvmBevdcNtOdhJX8W1yzAABH1HjWAvaSclBhrBEVP5OFQdAiQ3BUP4TU/+uG9OmhJ9AaFhz3o175bFBrrBWAXUebFKW6g/Fz+7PKT3W1aRW0TIA+MJCvJJ+L1w/X6bFxeXfWuIX63fSo9gvMSw4no=
